version: 2
updates:
  - package-ecosystem: bun
    directory: "/"
    schedule:
      interval: monthly
    groups:
      patch-updates:
        update-types: ["patch"]
      minor-updates:
        update-types: ["minor"]
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "ci"
    commit-message:
      prefix: "ci"
